config/routes.rb
Corkboard::Application.routes.draw do
  root :to => 'covers#index'

  get "adminpanel/index"

  get "sessions/new"
  get "sessions/destroy"
  get "users/new"

  get "covers/index"

  get "cover/index"

  post "management/themeUpdate"

  resources :posts do
    resources :boards
    resources :comments
  end

  resources :boards do
    resources :posts
  end

  resources :sessions
  resources :management
  
  match '/login' => 'sessions#index'
  match '/logout' => 'sessions#destroy', :method => :delete 
  match '/register' => 'users#new'
  match '/sessions' => 'sessions#index'
  match 'system-manage' => 'management#index'
  match 'system-manage/boards' => 'management#boards'
  match 'system-manage/users' => 'management#users'
  match 'system-manage/plugins' => 'management#plugins'
  match 'system-manage/themes' => 'management#themes'

  resources :users

end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
	def index

	end

	def boards
		@boards = Board.all
	end
	def users
		@users = User.all
	end

	def login
		if current_user
		if current_user.admin
			redirect_to :action => 'index'
		end
		end
	end
	def themes
      dir = 'public/themes/*'
      @dirs = Dir.glob(dir).select {|f| File.directory? f}
      @files = Dir.glob(dir).select {|f| File.file? (f)} 
      @theme_now = Settings.theme_path
	end
	def themeUpdate
		@theme = params[:theme]
		respond_to do |format|
			target  = Rails.root.join('config', 'config.yml')
			File.open(target, "w+") do |f|
  			f.write("defaults: &DEFAULTS
  theme_path: "+@theme+"
development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS")
  		format.html { redirect_to '/system-manage/themes/', notice: 'HUGE SUCCESS!' }
			end
		end
	end
end
class Settings < Settingslogic
  source Rails.root.join('config', 'config.yml')
  namespace Rails.env
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/views/management/boards.html.erb
<% if current_user %>
<% if current_user.admin%>

<div class="container-fluid">
		<h1>Management.</h1>

  <div class="row-fluid">
    <div class="span2">
        <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Board
  </li>
    <li>
      <%= link_to "Boards", :controller => 'management', :action => :boards %>
</li>
  <li class="divider"></li>

  <li class="nav-header">
    ETC
  </li>
  <li>
      <%= link_to "Users", :controller => 'management', :action => :users %>
</li>
  <li>
      <%= link_to "Plugins", :controller => 'management', :action => :plugins %>

</li>
  <li>
      <%= link_to "Themes", :controller => 'management', :action => :themes %>
</li>
</ul>
        </div>
    </div>
    <div class="span10">
      <table class='table table-bordered table-condensed'>
  <thead>
    <tr>
      <td><%= link_to "New board", :controller => "boards", :action => 'new' %></td>
    </tr>
  </thead>
  <tbody>
  <% @boards.each do |board| %>
  <tr>
    <td><%= link_to board.name, :controller => "boards", :board => board.id %></td>
    <td><%= link_to 'Edit', edit_board_path(board) %></td>
    <td><%= link_to 'Destroy', board, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
  <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

	<% else %>
	You are not admin
<% end %>
<% else %>
Please log-in
<%= render :template => 'sessions/new' %>
<% end %>

app/views/management/index.html.erb
<% if current_user %>
<% if current_user.admin%>

<div class="container-fluid">
		<h1>Management.</h1>

  <div class="row-fluid">
    <div class="span2">
        <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Board
  </li>
    <li>
      <%= link_to "Boards", :controller => 'management', :action => :boards %>
</li>
  <li class="divider"></li>

  <li class="nav-header">
    ETC
  </li>
  <li>
      <%= link_to "Users", :controller => 'management', :action => :users %>
</li>
  <li>
      <%= link_to "Plugins", :controller => 'management', :action => :plugins %>

</li>
  <li>
      <%= link_to "Themes", :controller => 'management', :action => :themes %>
</li>


</ul>
        </div>
    </div>
    <div class="span10">
      <!--Body content-->
      <h1>Under construction.</h1>
    </div>
  </div>
</div>

	<% else %>
	You are not admin
<% end %>
<% else %>
Please log-in
<%= render :template => 'sessions/new' %>
<% end %>

app/views/management/login.html.erb
<% if current_user %>
<% if current_user.admin%>
	<% else %>
	You are not admin
<% end %>
<% else %>
Please log-in
<% end %>

app/views/management/plugins.html.erb
<% if current_user %>
<% if current_user.admin%>

<div class="container-fluid">
		<h1>Management.</h1>

  <div class="row-fluid">
    <div class="span2">
        <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Board
  </li>
    <li>
      <%= link_to "Boards", :controller => 'management', :action => :boards %>
</li>
  <li class="divider"></li>

  <li class="nav-header">
    ETC
  </li>
  <li>
      <%= link_to "Users", :controller => 'management', :action => :users %>
</li>
  <li>
      <%= link_to "Plugins", :controller => 'management', :action => :plugins %>

</li>
  <li>
      <%= link_to "Themes", :controller => 'management', :action => :themes %>
</li>

</ul>
        </div>
    </div>
    <div class="span10">
      Under Construction.
    </div>
  </div>
</div>

	<% else %>
	You are not admin
<% end %>
<% else %>
Please log-in
<%= render :template => 'sessions/new' %>
<% end %>

app/views/management/themes.html.erb
<% if current_user %>
<% if current_user.admin%>
<% else %>
You are not admin
<% end %>
<% else %>
Please log-in
<%= render :template => 'sessions/new' %>
<% end %>
<div class="container-fluid">
		<h1>Management.</h1>

  <div class="row-fluid">
    <div class="span2">
        <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Board
  </li>
    <li>
      <%= link_to "Boards", :controller => 'management', :action => :boards %>
</li>
  <li class="divider"></li>

  <li class="nav-header">
    ETC
  </li>
  <li>
      <%= link_to "Users", :controller => 'management', :action => :users %>
</li>
  <li>
      <%= link_to "Plugins", :controller => 'management', :action => :plugins %>

</li>
  <li>
      <%= link_to "Themes", :controller => 'management', :action => :themes %>
</li>


</ul>
        </div>
    </div>
    <div class="span10">
      Selected Theme : <%= @theme_now %>
<%= form_tag(:action=>:themeUpdate, :method=>'post') do -%>
<select id='theme' name='theme'>
<% @dirs.each do |dir| %>
    <option ><%= File.basename(dir) %></option>
<% end %>

</select>

   <%= submit_tag 'Change theme' %>
   <% end -%>
  </div>
</div>

app/views/management/users.html.erb
<% if current_user %>
<% if current_user.admin%>

<div class="container-fluid">
		<h1>Management.</h1>

  <div class="row-fluid">
    <div class="span2">
        <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Board
  </li>
    <li>
      <%= link_to "Boards", :controller => 'management', :action => :boards %>
</li>
  <li class="divider"></li>

  <li class="nav-header">
    ETC
  </li>
  <li>
      <%= link_to "Users", :controller => 'management', :action => :users %>
</li>
  <li>
      <%= link_to "Plugins", :controller => 'management', :action => :plugins %>

</li>
  <li>
      <%= link_to "Themes", :controller => 'management', :action => :themes %>
</li>


</ul>
        </div>
    </div>
    <div class="span10">
      <!--Body content-->
            <table class='table table-bordered table-condensed'>
  <thead>
    <tr>
      <td>Name</td>
      <td>Admin</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
  <% end %>
  </tbody>
</table>

    </div>
  </div>
</div>

	<% else %>
	You are not admin
<% end %>
<% else %>
Please log-in
<%= render :template => 'sessions/new' %>
<% end %>