config/routes.rb
Corkboard::Application.routes.draw do
  root :to => 'covers#index'

  get "adminpanel/index"

  get "sessions/new"
  get "sessions/destroy"
  get "users/new"

  get "covers/index"

  get "cover/index"

  post "management/themeUpdate"

  resources :posts do
    resources :boards
    resources :comments
  end

  resources :boards do
    resources :posts
  end

  resources :sessions
  resources :management
  
  match '/login' => 'sessions#index'
  match '/logout' => 'sessions#destroy', :method => :delete 
  match '/register' => 'users#new'
  match '/sessions' => 'sessions#index'
  match 'system-manage' => 'management#index'
  match 'system-manage/boards' => 'management#boards'
  match 'system-manage/users' => 'management#users'
  match 'system-manage/plugins' => 'management#plugins'
  match 'system-manage/themes' => 'management#themes'

  resources :users

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :content, :name, :title, :board_id,:board
  has_many :posts
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
    @board = Board.find(params[:board])
    @posts = Post.where(:board_id => (params[:board])).all(:order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<% if current_user %>
<% if current_user.admin%>

<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>
<% end %>
<% else %>
You are not admin.
<% end %>

app/views/boards/edit.html.erb
<% if current_user %>
<% if current_user.admin%>

<div class="container-fluid">
		<h1>Management.</h1>

  <div class="row-fluid">
    <div class="span2">
        <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Board
  </li>
    <li>
    <a href='/system-manage/boards'>Boards</a>
</li>
  <li class="divider"></li>

  <li class="nav-header">
    ETC
  </li>
  <li>
    <a href='/system-manage/users'>Users</a>

</li>
  <li>
    <a href='/system-manage/plugins'>Plugins</a>

</li>
  <li>
    <a href='/system-manage/themes'>Themes</a>
</li>
</ul>
        </div>
    </div>
    <div class="span10">
<%= render 'form' %>
    </div>
  </div>
</div>

	<% else %>
	You are not admin
<% end %>
<% else %>
Please log-in
<%= render :template => 'sessions/new' %>
<% end %>

app/views/boards/index.html.erb
<div class="container-fluid">
    <h1>Corkboard.</h1>

  <div class="row-fluid">
    <div class="span2">
            <div class="container-login">
  <div class='well'>

      <% if !current_user %>
            <%= render :template => 'sessions/new' %>
<% end %>
<% if current_user %>
<% if current_user.admin%>
<%= link_to 'Logout', :controller => "sessions" , :action => 'destroy', method: :delete %>
|
<%= link_to 'Management', 'system-manage' %>

<p><%= current_user.name %></p>

<% else %>
<% end %>
<%if !current_user.admin%>
<%= link_to 'Logout', :controller => "sessions" , :action => 'destroy', method: :delete %>
<% end %>
<% end %>
</div>
</div>

      <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Boards
  </li>
  <% @boards.each do |board| %>
  <li>
  <%= link_to board.name, :controller => "boards", :board => board.id %>
  
</li>
  <% end %>
</ul>
</div>
    </div>
    <div class="span10">
<p id="notice"><%= notice %></p>
<p>
  <%= @board.name %>
</p>

<h3>Posts</h3>
<table class='table'>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Author</th>
  </tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= link_to post.title,post %></td>
    <td><%= post.author %></td>
  </tr>
<% end %>
</table>
        <% if current_user %>
        <p><%= link_to "New Post", :controller => "posts", :action => 'new', :board => @board.id %></p>
        <% end %>
</div>    </div>
  </div>
</div>

app/views/boards/new.html.erb
<% if current_user %>
<% if current_user.admin%>

<div class="container-fluid">
		<h1>Management.</h1>

  <div class="row-fluid">
    <div class="span2">
        <div class='well'>
   <ul class="nav nav-list">
  <li class="nav-header">
    Board
  </li>
    <li>
    <a href='/system-manage/boards'>Boards</a>
</li>
  <li class="divider"></li>

  <li class="nav-header">
    ETC
  </li>
  <li>
    <a href='/system-manage/users'>Users</a>

</li>
  <li>
    <a href='/system-manage/plugins'>Plugins</a>

</li>
  <li>
    <a href='/system-manage/themes'>Themes</a>
</li>
</ul>
        </div>
    </div>
    <div class="span10">
<%= render 'form' %>
    </div>
  </div>
</div>

	<% else %>
	You are not admin
<% end %>
<% else %>
Please log-in
<%= render :template => 'sessions/new' %>
<% end %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @board.name %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>